channels:
  - https://prefix.dev/conda-forge
  - https://prefix.dev/bioconda
  - nodefaults
dependencies:
  - r-seurat =5.3.1
  - r-seuratobject =5.2.0
  - bioconductor-biocparallel =1.40.0
  - r-dt =0.34.0
  - r-hmisc =5.2_4
  - r-ggplot2 =4.0.0
  - r-ggpubr =0.6.2
  - r-rstatix =0.7.3
  - r-knitr =1.50
  - r-dplyr =1.1.4
  - r-coin =1.4_3
  - r-rmdformats =1.0.4
  - r-rmarkdown =2.30
  - bioconductor-singlecellexperiment =1.28.0
  - bioconductor-clusterprofiler =4.14.0
  - bioconductor-dose =4.0.0
  - bioconductor-org.mm.eg.db =3.20.0
  - bioconductor-gseabase =1.68.0
  - bioconductor-limma =3.62.1
  - bioconductor-deseq2 =1.46.0
  - r-remotes =2.5.0
  - r-git2r =0.35.0
  - r-upsetr =1.4.0
  - r-cairo =1.7_0
  - r-ggupset =0.4.1
  - bioconductor-pathview =1.46.0
  - bioconductor-enhancedvolcano =1.24.0
  - bioconductor-escape =2.2.0
  - bioconductor-dittoseq =1.18.0
  - bioconductor-complexheatmap =2.22.0
